version: '3.8'

services:
  # Node.js API Service
  api:
    build: .
    container_name: petshop_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://host.docker.internal:27017/petshop
      PORT: 5000
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"